"""initial schema

Revision ID: 5589e602eefa
Revises:
Create Date: 2026-08-13 09:15:32.831381

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5589e602eefa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_agent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_name", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(op.f("ix_dim_agent_agent_name"), "dim_agent", ["agent_name"], unique=True, schema="fines")
    op.create_table(
        "dim_carrier",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("carrier_id", sa.String(length=20), nullable=False),
        sa.Column("carrier_name", sa.String(length=100), nullable=False),
        sa.Column("historical_reliability_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_dim_carrier_carrier_id"), "dim_carrier", ["carrier_id"], unique=True, schema="fines"
    )
    op.create_table(
        "dim_location",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.String(length=20), nullable=False),
        sa.Column("location_name", sa.String(length=100), nullable=True),
        sa.Column("location_type", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_dim_location_location_id"), "dim_location", ["location_id"], unique=True, schema="fines"
    )
    op.create_table(
        "dim_retailer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("retailer_id", sa.String(length=20), nullable=False),
        sa.Column("retailer_name", sa.String(length=100), nullable=False),
        sa.Column("priority_tier", sa.String(length=20), nullable=True),
        sa.Column("stacking_mode", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_dim_retailer_retailer_id"), "dim_retailer", ["retailer_id"], unique=True, schema="fines"
    )
    op.create_table(
        "dim_sku",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.String(length=20), nullable=False),
        sa.Column("sku_code", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(op.f("ix_dim_sku_sku_id"), "dim_sku", ["sku_id"], unique=True, schema="fines")
    op.create_table(
        "dim_fine_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("retailer_id", sa.String(length=20), nullable=False),
        sa.Column("violation_type", sa.String(length=30), nullable=False),
        sa.Column("threshold_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("calc_type", sa.String(length=20), nullable=False),
        sa.Column("rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("cap_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("grace_period_days", sa.Integer(), nullable=False),
        sa.Column("effective_start_date", sa.Date(), nullable=False),
        sa.Column("effective_end_date", sa.Date(), nullable=True),
        sa.Column("source_doc_reference", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["fines.dim_retailer.retailer_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_dim_fine_rule_rule_id"), "dim_fine_rule", ["rule_id"], unique=True, schema="fines"
    )
    op.create_table(
        "dim_prompt_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("module_path", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["fines.dim_agent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "prompt_version", name="uq_prompt_version_agent_version"),
        schema="fines",
    )
    op.create_table(
        "fact_order",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("retailer_id", sa.String(length=20), nullable=False),
        sa.Column("sku_id", sa.String(length=20), nullable=False),
        sa.Column("ship_from_location_id", sa.String(length=20), nullable=False),
        sa.Column("order_qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("requested_delivery_date", sa.Date(), nullable=False),
        sa.Column("required_ship_date", sa.Date(), nullable=False),
        sa.Column("order_status", sa.String(length=20), nullable=False),
        sa.Column("carrier_id", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["fines.dim_carrier.carrier_id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["fines.dim_retailer.retailer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["ship_from_location_id"],
            ["fines.dim_location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["fines.dim_sku.sku_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(op.f("ix_fact_order_order_id"), "fact_order", ["order_id"], unique=True, schema="fines")
    op.create_table(
        "fact_production_schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("production_id", sa.String(length=40), nullable=False),
        sa.Column("sku_id", sa.String(length=20), nullable=False),
        sa.Column("location_id", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["fines.dim_location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["fines.dim_sku.sku_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_fact_production_schedule_production_id"),
        "fact_production_schedule",
        ["production_id"],
        unique=True,
        schema="fines",
    )
    op.create_table(
        "dim_fine_rule_tier",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tier_id", sa.String(length=40), nullable=False),
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("band_min", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("band_max", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["fines.dim_fine_rule.rule_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_dim_fine_rule_tier_tier_id"), "dim_fine_rule_tier", ["tier_id"], unique=True, schema="fines"
    )
    op.create_table(
        "fact_actual_fine",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actual_fine_id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("retailer_id", sa.String(length=20), nullable=False),
        sa.Column("violation_type", sa.String(length=30), nullable=False),
        sa.Column("actual_fine_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("invoice_or_deduction_date", sa.Date(), nullable=False),
        sa.Column("dispute_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["fines.dim_retailer.retailer_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_fact_actual_fine_actual_fine_id"),
        "fact_actual_fine",
        ["actual_fine_id"],
        unique=True,
        schema="fines",
    )
    op.create_table(
        "fact_demand_exception",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exception_id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("flagged_date", sa.Date(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_fact_demand_exception_exception_id"),
        "fact_demand_exception",
        ["exception_id"],
        unique=True,
        schema="fines",
    )
    op.create_table(
        "fact_fine_summary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id", "prompt_version"],
            ["fines.dim_prompt_version.agent_id", "fines.dim_prompt_version.prompt_version"],
            name="fk_fine_summary_agent_prompt_version",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "as_of_date", "prompt_version", name="uq_fine_summary_order_date_prompt"
        ),
        schema="fines",
    )
    op.create_table(
        "fact_order_confirmation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("confirmation_id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("confirmed_qty", sa.Integer(), nullable=False),
        sa.Column("confirmation_date", sa.DateTime(), nullable=False),
        sa.Column("cut_reason_code", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_fact_order_confirmation_confirmation_id"),
        "fact_order_confirmation",
        ["confirmation_id"],
        unique=True,
        schema="fines",
    )
    op.create_table(
        "fact_projected_fine",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("rule_id", sa.String(length=20), nullable=False),
        sa.Column("projection_date", sa.Date(), nullable=False),
        sa.Column("violation_type", sa.String(length=30), nullable=False),
        sa.Column("failure_probability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("projected_fine_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("days_to_delivery", sa.Integer(), nullable=False),
        sa.Column("projection_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["fines.dim_fine_rule.rule_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "rule_id", "projection_date", name="uq_projected_fine_order_rule_date"
        ),
        schema="fines",
    )
    op.create_table(
        "fact_shipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("carrier_id", sa.String(length=20), nullable=True),
        sa.Column("expected_ship_date", sa.Date(), nullable=True),
        sa.Column("actual_ship_date", sa.Date(), nullable=True),
        sa.Column("appointment_status", sa.String(length=20), nullable=False),
        sa.Column("expected_transit_days", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["fines.dim_carrier.carrier_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        op.f("ix_fact_shipment_shipment_id"), "fact_shipment", ["shipment_id"], unique=True, schema="fines"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fact_shipment_shipment_id"), table_name="fact_shipment", schema="fines")
    op.drop_table("fact_shipment", schema="fines")
    op.drop_table("fact_projected_fine", schema="fines")
    op.drop_index(
        op.f("ix_fact_order_confirmation_confirmation_id"),
        table_name="fact_order_confirmation",
        schema="fines",
    )
    op.drop_table("fact_order_confirmation", schema="fines")
    op.drop_table("fact_fine_summary", schema="fines")
    op.drop_index(
        op.f("ix_fact_demand_exception_exception_id"), table_name="fact_demand_exception", schema="fines"
    )
    op.drop_table("fact_demand_exception", schema="fines")
    op.drop_index(op.f("ix_fact_actual_fine_actual_fine_id"), table_name="fact_actual_fine", schema="fines")
    op.drop_table("fact_actual_fine", schema="fines")
    op.drop_index(op.f("ix_dim_fine_rule_tier_tier_id"), table_name="dim_fine_rule_tier", schema="fines")
    op.drop_table("dim_fine_rule_tier", schema="fines")
    op.drop_index(
        op.f("ix_fact_production_schedule_production_id"),
        table_name="fact_production_schedule",
        schema="fines",
    )
    op.drop_table("fact_production_schedule", schema="fines")
    op.drop_index(op.f("ix_fact_order_order_id"), table_name="fact_order", schema="fines")
    op.drop_table("fact_order", schema="fines")
    op.drop_table("dim_prompt_version", schema="fines")
    op.drop_index(op.f("ix_dim_fine_rule_rule_id"), table_name="dim_fine_rule", schema="fines")
    op.drop_table("dim_fine_rule", schema="fines")
    op.drop_index(op.f("ix_dim_sku_sku_id"), table_name="dim_sku", schema="fines")
    op.drop_table("dim_sku", schema="fines")
    op.drop_index(op.f("ix_dim_retailer_retailer_id"), table_name="dim_retailer", schema="fines")
    op.drop_table("dim_retailer", schema="fines")
    op.drop_index(op.f("ix_dim_location_location_id"), table_name="dim_location", schema="fines")
    op.drop_table("dim_location", schema="fines")
    op.drop_index(op.f("ix_dim_carrier_carrier_id"), table_name="dim_carrier", schema="fines")
    op.drop_table("dim_carrier", schema="fines")
    op.drop_index(op.f("ix_dim_agent_agent_name"), table_name="dim_agent", schema="fines")
    op.drop_table("dim_agent", schema="fines")
    # ### end Alembic commands ###
