"""job queue and fine summary fingerprint columns

Revision ID: ff84c023d5e9
Revises: 8209afe73fa4
Create Date: 2026-08-13 20:26:13.779591

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff84c023d5e9"
# Rebased onto the cmir merge's head instead of 5589e602eefa directly (its
# original parent, written before the cmir merge existed) -- this branch's
# job_run/job_item tables are fines-only and independent of cmir's, so this
# is a down_revision pointer fix, not a schema-level reconciliation.
down_revision: str | None = "8209afe73fa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _add_column_schema() -> str | None:
    """Schema to pass to op.add_column/op.drop_column for this migration.

    Unlike op.create_table/op.create_index, Alembic's ADD COLUMN/DROP
    COLUMN DDL for SQLite renders the schema-qualified table name
    (`fines.fact_fine_summary`) directly rather than through the
    connection's `schema_translate_map` -- so on SQLite (the dialect
    tests/test_migration_parity.py runs this migration against) the
    literal string `"fines.fact_fine_summary"` is passed straight to
    sqlite3 and fails with "no such table", even though the table exists
    unqualified. Same no-op-on-SQLite gating style as
    alembic/env.py::_version_table_schema.
    """
    return None if op.get_bind().dialect.name == "sqlite" else "fines"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_type", sa.String(length=20), nullable=False),
        sa.Column("projection_date", sa.Date(), nullable=False),
        sa.Column("stacking_mode_override", sa.String(length=10), nullable=True),
        sa.Column("triggered_by", sa.String(length=100), nullable=True),
        sa.Column("requested_item_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "run_type IN ('SCHEDULED_DAILY', 'MANUAL_BATCH', 'ON_DEMAND')", name="ck_job_run_run_type"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_table(
        "job_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_run_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.String(length=30), nullable=False),
        sa.Column("projection_date", sa.Date(), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("stacking_mode_override", sa.String(length=10), nullable=True),
        sa.Column("force_regenerate_summary", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_error_code", sa.String(length=50), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'DEAD')", name="ck_job_item_status"
        ),
        sa.CheckConstraint("task_type IN ('ORDER_RUN', 'SUMMARY_REGEN')", name="ck_job_item_task_type"),
        sa.ForeignKeyConstraint(
            ["job_run_id"],
            ["fines.job_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["fines.fact_order.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fines",
    )
    op.create_index(
        "ix_job_item_claimable", "job_item", ["status", "available_at"], unique=False, schema="fines"
    )
    op.create_index("ix_job_item_job_run_id", "job_item", ["job_run_id"], unique=False, schema="fines")
    # Partial unique index -- deliberately NOT expressible via the ORM model
    # (SQLAlchemy's `postgresql_where=` on an `Index` is silently dropped on
    # SQLite, which would otherwise create a *full* unique index in the
    # SQLite test database and wrongly reject a legitimate second terminal
    # (SUCCEEDED/DEAD) row for the same order/date/task). Raw DDL only; see
    # app/models/job_queue.py::JobItem docstring and docs/DATABASE.md for the
    # full explanation, including why tests/test_migration_parity.py cannot
    # catch a divergence here (it only compares table/column names, not
    # indexes).
    #
    # Branched by dialect, not left Postgres-only: tests/test_migration_parity.py
    # runs this exact migration against a SQLite database, and the
    # `fines.` schema qualifier below only gets stripped for compiled
    # Table/Column DDL via `apply_sqlite_schema_translation`'s
    # schema_translate_map (see app/db/session.py, alembic/env.py) -- it is
    # never applied to a raw SQL string passed to `op.execute`. SQLite does
    # support the same partial-index syntax, so the fallback below is a
    # real (if untranslated-schema) equivalent, not a stub -- it just has to
    # spell the table name unqualified.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE UNIQUE INDEX uq_job_item_inflight ON fines.job_item "
            "(order_id, projection_date, task_type) WHERE status IN ('PENDING', 'RUNNING')"
        )
    else:
        op.execute(
            "CREATE UNIQUE INDEX uq_job_item_inflight ON job_item "
            "(order_id, projection_date, task_type) WHERE status IN ('PENDING', 'RUNNING')"
        )
    op.add_column(
        "fact_fine_summary",
        sa.Column("content_fingerprint", sa.String(length=64), nullable=True),
        schema=_add_column_schema(),
    )
    op.add_column(
        "fact_fine_summary",
        sa.Column("source_as_of_date", sa.Date(), nullable=True),
        schema=_add_column_schema(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fact_fine_summary", "source_as_of_date", schema=_add_column_schema())
    op.drop_column("fact_fine_summary", "content_fingerprint", schema=_add_column_schema())
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX fines.uq_job_item_inflight")
    else:
        op.execute("DROP INDEX uq_job_item_inflight")
    op.drop_index("ix_job_item_job_run_id", table_name="job_item", schema="fines")
    op.drop_index("ix_job_item_claimable", table_name="job_item", schema="fines")
    op.drop_table("job_item", schema="fines")
    op.drop_table("job_run", schema="fines")
    # ### end Alembic commands ###
