"""Register and re-export all ORM models so they are available through
`app.models`.

Four Postgres schemas: `common` (shared master/fulfillment data), `process`
(shared job/agent/workflow backbone), `cmir` (CMIR-only), `penalties`
(penalties-only). No tables in `public`. See docs/DATABASE.md and
`app/db/base.py` for the schema constants.
"""

from app.db.base import Base, TimestampMixin
from app.models.cmir import (
    CmirJobItemContext,
    CmirJobRunContext,
    CmirRecord,
    EmailActionLog,
    EmailEvent,
)
from app.models.common import (
    Carrier,
    Delivery,
    DeliveryLine,
    DemandException,
    Material,
    MaterialMaster,
    OrderConfirmation,
    OrderConfirmationLine,
    Plant,
    PoDeliveryChangeRequest,
    ProductionOrder,
    ProductionSchedule,
    PurchaseOrder,
    PurchaseOrderLine,
    Retailer,
    RetailerLocation,
    Shipment,
    Sku,
    StorageLocation,
    Warehouse,
)
from app.models.enums import AgentDomain, JobItemStatus, JobRunType, JobTaskType, SummaryStatus, SummaryType
from app.models.penalties import (
    ActualPenalty,
    MitigationInput,
    MitigationOption,
    PenaltyJobItemContext,
    PenaltyJobRunContext,
    PenaltyProjection,
    PenaltyRule,
    PenaltyRuleTier,
    PenaltySummary,
)
from app.models.process import (
    Agent,
    AgentRun,
    AgentTrace,
    HumanAction,
    JobItem,
    JobRun,
    ProcessingError,
    WorkflowThread,
    WorkflowThreadSubject,
)

__all__ = [
    "ActualPenalty",
    "Agent",
    "AgentDomain",
    "AgentRun",
    "AgentTrace",
    "Base",
    "Carrier",
    "CmirJobItemContext",
    "CmirJobRunContext",
    "CmirRecord",
    "Delivery",
    "DeliveryLine",
    "DemandException",
    "EmailActionLog",
    "EmailEvent",
    "HumanAction",
    "JobItem",
    "JobItemStatus",
    "JobRun",
    "JobRunType",
    "JobTaskType",
    "Material",
    "MaterialMaster",
    "MitigationInput",
    "MitigationOption",
    "OrderConfirmation",
    "OrderConfirmationLine",
    "PenaltyJobItemContext",
    "PenaltyJobRunContext",
    "PenaltyProjection",
    "PenaltyRule",
    "PenaltyRuleTier",
    "PenaltySummary",
    "Plant",
    "PoDeliveryChangeRequest",
    "ProcessingError",
    "ProductionOrder",
    "ProductionSchedule",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "Retailer",
    "RetailerLocation",
    "Shipment",
    "Sku",
    "StorageLocation",
    "SummaryStatus",
    "SummaryType",
    "TimestampMixin",
    "Warehouse",
    "WorkflowThread",
    "WorkflowThreadSubject",
]
